spring:
  application:
    name: FoobarShipping
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${FOOBAR_DDL_AUTO:none}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        auto_quote_keyword: true
  datasource:
    hikari:
      maximum-pool-size: 64
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      okhttp:
        enabled: true


server:
  port: ${FOOBAR_SERVICE_PORT_SHIPPING:4044}
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    org.apache.kafka: ${FOOBAR_LOG_LEVEL_KAFKA:warn}
    org.springframework.kafka: ${FOOBAR_LOG_LEVEL_KAFKA:warn}
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}


foobar:
  service:
    services:
      customer:
        url: ${FOOBAR_SERVICE_URL_CUSTOMER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_CUSTOMER:4040}
      seller:
        url: ${FOOBAR_SERVICE_URL_SELLER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_SELLER:4043}
      marketplace:
        url: ${FOOBAR_SERVICE_URL_MARKETPLACE:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_MARKETPLACE:4041}


management:
  observations:
    key-values:
      foobar-service: foobar-shipping
  endpoints:
    web:
      exposure:
        include:
          - '*'
