spring:
  config:
    activate:
      on-profile:
        - db-postgres
  datasource:
    url: jdbc:postgresql://${FOOBAR_POSTGRES_HOST:localhost:5432}/foobar_shipping
    username: ${FOOBAR_POSTGRES_USER:root}
    password: ${FOOBAR_POSTGRES_PASS:.}
