spring:
  application:
    name: FoobarWarehouse
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${FOOBAR_DDL_AUTO:none}
    properties:
      hibernate:
        auto_quote_keyword: true
  zipkin:
    enabled: false


server:
  port: ${FOOBAR_SERVICE_PORT_WAREHOUSE:4046}
  error:
    include-message: always
    include-binding-errors: always


feign:
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000


resilience4j:
  circuitbreaker:
    instances:
      seller-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 10
  retry:
    instances:
      seller-service:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException


logging:
  level:
    org.apache.kafka: error
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}
    org.mariadb.jdbc.message.server.ErrorPacket: error
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: error


foobar:
  service:
    services:
      seller:
        url: ${FOOBAR_SERVICE_URL_SELLER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_SELLER:4043}
        retry: true
        limit: false
  rest:
    on-concurrency-error-retry-after: 1s

management:
  metrics:
    tags:
      foobar-service: foobar-warehouse
  endpoints:
    web:
      exposure:
        include:
          - '*'
