spring:
  application:
    name: FoobarWarehouse
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${FOOBAR_DDL_AUTO:none}
    properties:
      hibernate:
        auto_quote_keyword: true
  datasource:
    hikari:
      maximum-pool-size: 64
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      okhttp:
        enabled: true


server:
  port: ${FOOBAR_SERVICE_PORT_WAREHOUSE:4046}
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    org.apache.kafka: ${FOOBAR_LOG_LEVEL_KAFKA:warn}
    org.springframework.kafka: ${FOOBAR_LOG_LEVEL_KAFKA:warn}
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}


foobar:
  service:
    services:
      seller:
        url: ${FOOBAR_SERVICE_URL_SELLER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_SELLER:4043}


management:
  observations:
    key-values:
      foobar-service: foobar-warehouse
  endpoints:
    web:
      exposure:
        include:
          - '*'
