global:
  kibanaEnabled: true

master:
  replicaCount: 1

data:
  replicaCount: 1

coordinating:
  replicaCount: 1

ingest:
  replicaCount: 1

kibana:
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: false

volumePermissions:
  enabled: true

kibana:
  volumePermissions:
    enabled: true

