spring:
  application:
    name: FoobarLoader
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      okhttp:
        enabled: true


logging:
  level:
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}


foobar:
  port:
    marketplace: ${FOOBAR_SERVICE_PORT_MARKETPLACE:4041}
    warehouse: ${FOOBAR_SERVICE_PORT_WAREHOUSE:4046}
    customer: ${FOOBAR_SERVICE_PORT_CUSTOMER:4040}
    seller: ${FOOBAR_SERVICE_PORT_SELLER:4043}
    # shipping: ${FOOBAR_SERVICE_PORT_SHIPPING:4044}
  url:
    # defaultUrl: ${FOOBAR_URL_DEFAULT:http://localhost}
    marketplace: ${FOOBAR_URL_MARKETPLACE:http://localhost}
    warehouse: ${FOOBAR_URL_WAREHOUSE:http://localhost}
    customer: ${FOOBAR_URL_CUSTOMER:http://localhost}
    seller: ${FOOBAR_URL_SELLER:http://localhost}
    # shipping: ${FOOBAR_URL_SHIPPING:http://localhost}


management:
  observations:
    key-values:
      foobar-service: foobar-loader
  endpoints:
    web:
      exposure:
        include:
          - '*'
