{
 "title": "Foobar Customer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Warehouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get Product Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"GET\",status=\"200\",uri=\"/foobar/warehouse/v1/products/{productId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"GET\",status!=\"200\",uri=\"/foobar/warehouse/v1/products/{productId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Product Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"POST\",status=\"201\",uri=\"/foobar/warehouse/v1/products\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"POST\",status!=\"201\",uri=\"/foobar/warehouse/v1/products\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Availability Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"POST\",status=\"201\",uri=\"/foobar/warehouse/v1/products/{productId}/availabilities\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-warehouse\",method=\"POST\",status!=\"201\",uri=\"/foobar/warehouse/v1/products/{productId}/availabilities\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Marketplace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Seller Result Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(seller_found_total{\n    foobar_service=\"foobar-marketplace\"\n}[$__rate_interval]))",
     "legendFormat": "Found"
    },
    {
     "expr": "sum(rate(seller_not_found_total{\n    foobar_service=\"foobar-marketplace\"\n}[$__rate_interval]))",
     "legendFormat": "Not Found"
    }
   ]
  },
  {
   "title": "Seller Result %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "100 * sum(rate(seller_not_found_total{\n    foobar_service=\"foobar-marketplace\"\n}[$__rate_interval])) \n/ \n(\n    sum(rate(seller_found_total{\n        foobar_service=\"foobar-marketplace\"\n    }[$__rate_interval]))\n    +\n    sum(rate(seller_not_found_total{\n        foobar_service=\"foobar-marketplace\"\n    }[$__rate_interval])) \n)",
     "legendFormat": "NotFound%"
    }
   ]
  },
  {
   "title": "Patch Order Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"PATCH\",status=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"PATCH\",status!=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Order Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"POST\",status=\"200\",uri=\"/foobar/marketplace/v1/order-requests\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"POST\",status!=\"200\",uri=\"/foobar/marketplace/v1/order-requests\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Line Item Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"POST\",status=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}/line-items\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"POST\",status!=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}/line-items\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Get Line Item Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"GET\",status=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}/line-items\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-marketplace\",method=\"GET\",status!=\"200\",uri=\"/foobar/marketplace/v1/order-requests/{orderRequestId}/line-items\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Marketplace Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "State Change Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(onEntityStateChanged_seconds_count{\n    foobar_service=\"foobar-marketplace-engine\"\n}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "State Change Processed Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(onEntityStateChanged_seconds_sum{\n    foobar_service=\"foobar-marketplace-engine\"\n}[$__rate_interval]))\n/\nsum(rate(onEntityStateChanged_seconds_count{\n    foobar_service=\"foobar-marketplace-engine\"\n}[$__rate_interval]))",
     "legendFormat": "Success"
    }
   ]
  },
  { "title": "Seller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Get Seller RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"GET\",status=\"200\",uri=\"/foobar/seller/v1/sellers/{sellerId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"GET\",status!=\"200\",uri=\"/foobar/seller/v1/sellers/{sellerId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Seller RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"POST\",status=\"201\",uri=\"/foobar/seller/v1/sellers\"\n}[$__rate_interval]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"POST\",status!=\"201\",uri=\"/foobar/seller/v1/sellers\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Get Seller Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"GET\",status=\"200\",uri=\"/foobar/seller/v1/sellers/{sellerId}\"\n}[$__rate_interval]))\n/\nsum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"GET\",status=\"200\",uri=\"/foobar/seller/v1/sellers/{sellerId}\"\n}[$__rate_interval]))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Post Seller Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"POST\",status=\"201\",uri=\"/foobar/seller/v1/sellers\"\n}[$__rate_interval]))\n/\nsum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-seller\",method=\"POST\",status=\"201\",uri=\"/foobar/seller/v1/sellers\"\n}[$__rate_interval]))",
     "legendFormat": "Successful"
    }
   ]
  },
  { "title": "Customer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Get Customer RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status!=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Customer RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"POST\",status=\"201\",uri=\"/foobar/customer/v1/customers\",\n}[$__rate_interval]))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Get Customer Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\", method=\"GET\", status=\"200\", uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))\n/\nsum(increase(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\", method=\"GET\", status=\"200\", uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\", method=\"GET\", status!=\"200\", uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))\n/\nsum(increase(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\", method=\"GET\", status!=\"200\", uri=\"/foobar/customer/v1/customers/{customerId}\"\n}[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Customer Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\", method=\"POST\", status=\"201\", uri=\"/foobar/customer/v1/customers\"\n}[$__rate_interval]))\n/\nsum(increase(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\", method=\"POST\", status=\"201\", uri=\"/foobar/customer/v1/customers\"\n}[$__rate_interval]))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Get Addresses RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status!=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Address Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"POST\",status=\"201\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Get Addresses Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\",method=\"GET\",status=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n/\nsum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\",method=\"GET\",status!=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n/\nsum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"GET\",status!=\"200\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Post Address Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{\n    foobar_service=\"foobar-customer\",method=\"POST\",status=\"201\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n/\nsum(rate(http_server_requests_seconds_count{\n    foobar_service=\"foobar-customer\",method=\"POST\",status=\"201\",uri=\"/foobar/customer/v1/customers/{customerId}/addresses\"\n}[$__rate_interval]))\n",
     "legendFormat": "Successful"
    }
   ]
  }
 ]
}