{
 "title": "Foobar Maker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Maker Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of scraps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(maker_exporter__num_scraps{\n  foobar_tool=\"foobar-maker-exporter\", service=\"\"\n})",
     "legendFormat": "num_scraps"
    }
   ]
  },
  {
   "title": "Last Read",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "maker_exporter__last_successful_read{service=\"\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Marketplace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Create Line Order Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_order_request{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_order_request{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Order Request Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_order_request{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Create Line Items Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_line_item{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_line_item{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Line Items Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_line_item{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Order Request Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_ok__u_order_request{\n  service=\"\"\n})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(maker__ga_err__u_order_request{\n  service=\"\"\n})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Order Request Update Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_ok__u_order_request{\n  service=\"\"\n}",
     "legendFormat": "Successful"
    }
   ]
  },
  { "title": "Warehouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Create Product Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_product{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_product{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Product Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_product{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Create Availability Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_availability{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_availability{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Availability Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_availability{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Seller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Create Seller Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_seller{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_seller{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Seller Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_seller{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Customer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Create Customer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_customer{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_customer{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Customer Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_customer{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Create Address Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "tx/sec" } },
   "targets": [
    {
     "expr": "sum(maker__ga_err__c_address{\n    service=\"\"\n})",
     "legendFormat": " Failed"
    },
    {
     "expr": "sum(maker__ga_ok__c_address{\n    service=\"\"\n})",
     "legendFormat": " Ok"
    }
   ]
  },
  {
   "title": "Create Address Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms/tx" } },
   "targets": [
    {
     "expr": "maker__ga_timer__c_address{\n    service=\"\"\n}",
     "legendFormat": " "
    }
   ]
  }
 ]
}