apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    orgId: 1
    url: http://prometheus-kube-prometheus-prometheus:9090
    isDefault: true
    version: 1
    editable: true

