apiVersion: 1

datasources:
  - name: DS_PROMETHUES
    type: prometheus
    uid: foobar_prometheus
    access: server
    orgId: 1
    uid: prometheus
    url: http://prometheus-kube-prometheus-prometheus:9090
    isDefault: true
    version: 1
    editable: true

