apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foobar
spec:
  selector:
    matchLabels:
      foobarmonitoring: enabled
  endpoints:
  - port: server
    path: /actuator/prometheus
