version: "3"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    environment:
      - MARIADB_SKIP_TEST_DB=yes
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=.

volumes:
  mariadb_data:
    driver: local

