apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-warehouse
  labels:
    foobar-service: warehouse
    foobarmonitoring: enabled
spec:
  selector:
    matchLabels:
      foobar-service: warehouse
  replicas: ${FOOBAR_WAREHOUSE_REPLICAS}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        foobar-service: warehouse
        foobar-json-log: enabled
        foobarmonitoring: enabled
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10
      volumes:
        - name: foobar-log
          emptyDir: {}
      containers:
        - name: foobar-logger
          image: 'busybox'
          args: [/bin/sh, -c, 'tail -n+1 -F /foobar-log/foobar.log 2>/dev/null']
          volumeMounts:
            - name: foobar-log
              mountPath: /foobar-log
        - name: foobar-warehouse
          image: 'docker.io/library/foobar-warehouse:0.0.1-SNAPSHOT'
          imagePullPolicy: Never
          terminationMessagePolicy: File
          volumeMounts:
            - name: foobar-log
              mountPath: /foobar-log
          ports:
            - name: server
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'kafka,db-mysql,json-logging,expose,zipkin'
            - name: FOOBAR_LOG_LEVEL
              value: trace
            - name: FOOBAR_DDL_AUTO
              value: update
            - name: FOOBAR_SERVICE_PORT_WAREHOUSE
              value: '8080'
            - name: FOOBAR_MYSQL_HOST
              value: 'mariadb.foobar.svc.cluster.local:3306'
            - name: FOOBAR_MYSQL_USER
              value: root
            - name: FOOBAR_MYSQL_PASS
              value: '.'
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: 'http://jaeger-collector.foobar.svc.cluster.local:14250'
            - name: FOOBAR_KAFKA_BOOTSTRAP_SERVER
              value: 'kafka-0.kafka-headless.foobar.svc.cluster.local:9092'
            - name: FOOBAR_SERVICE_URL_SELLER
              value: 'http://foobar-seller.foobar.svc.cluster.local'
            - name: FOOBAR_SERVICE_PORT_SELLER
              value: '8080'
            - name: OTEL_METRICS_EXPORTER
              value: 'none'
            - name: FOOBAR_ZIPKIN_HOST
              value: 'http://zipkin:9411'
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: foobar-warehouse
    foobarmonitoring: enabled
  name: foobar-warehouse
spec:
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    foobar-service: warehouse
  type: ClusterIP

