spring:
  application:
    name: FoobarMarketplaceEngine
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${FOOBAR_DDL_AUTO:none}
    properties:
      hibernate:
        auto_quote_keyword: true
  cloud:
    loadbalancer:
      cache:
        enabled: false
  zipkin:
    enabled: false

server:
  port: ${FOOBAR_SERVICE_PORT_MARKETPLACE_ENGINE:4042}
  error:
    include-message: always
    include-binding-errors: always


feign:
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000


resilience4j:
  circuitbreaker:
    instances:
      seller-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 10

logging:
  level:
    org.apache.kafka: error
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}


foobar:
  rest:
    on-concurrency-error-retry-after: 10s

management:
  metrics:
    tags:
      foobar-service: foobar-marketplace-engine
  endpoints:
    web:
      exposure:
        include:
          - '*'
