allInOne:
  enabled: true

# storage:
#  type: cassandra

provisionDataStore:
  cassandra: false
  elasticsearch: false

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false

