spring:
  application:
    name: FoobarMaker
  main:
    banner-mode: off
    log-startup-info: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true

server:
  port: ${FOOBAR_SERVICE_PORT_MAKER:4048}
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%clr(%m) %n"
  level:
    org.hibernate: error
    org.springframework: error
    com.zaxxer: error

management:
  metrics:
    tags:
      foobar-service: foobar-maker
  endpoints:
    web:
      exposure:
        include:
          - '*'

foobar:
  port:
    marketplace: ${FOOBAR_SERVICE_PORT_MARKETPLACE:4041}
    warehouse: ${FOOBAR_SERVICE_PORT_WAREHOUSE:4046}
    shipping: ${FOOBAR_SERVICE_PORT_SHIPPING:4044}
    customer: ${FOOBAR_SERVICE_PORT_CUSTOMER:4040}
    seller: ${FOOBAR_SERVICE_PORT_SELLER:4043}
  url:
    defaultUrl: ${FOOBAR_URL_DEFAULT:http://localhost}
    marketplace: ${FOOBAR_URL_MARKETPLACE:}
    warehouse: ${FOOBAR_URL_WAREHOUSE:}
    shipping: ${FOOBAR_URL_SHIPPING:}
    customer: ${FOOBAR_URL_CUSTOMER:}
    seller: ${FOOBAR_URL_SELLER:}
