spring:
  config:
    activate:
      on-profile:
        - db-mysql
  datasource:
    url: jdbc:mariadb://${FOOBAR_MYSQL_HOST:localhost:3306}/foobar_maker
    username: ${FOOBAR_MYSQL_USER:root}
    password: ${FOOBAR_MYSQL_PASS:.}
