apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      zipkin: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        zipkin: zipkin
    spec:
      containers:
        - name: zipkin
          image: 'openzipkin/zipkin:latest'
          ports:
            - name: zipkin
              containerPort: 9411
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  ports:
    - name: http
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    zipkin: zipkin
  type: ClusterIP

