apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      zipkin: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        zipkin: zipkin
    spec:
      containers:
        - name: zipkin
          image: 'openzipkin/zipkin:latest'
          ports:
            - name: zipkin
              containerPort: 9411
              protocol: TCP
          env:
            - name: STORAGE_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: mariadb.foobar.svc.cluster.local
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: '.'
            - name: JAVA_OPTS
              value: '-verbose:gc -Xms512m -Xmx512m'

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  ports:
    - name: http
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    zipkin: zipkin
  type: ClusterIP

