
spring:
  application:
    name: FoobarCustomer
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${FOOBAR_DDL_AUTO:none}
    properties:
      hibernate:
        auto_quote_keyword: true
  zipkin:
    enabled: false
  datasource:
    hikari:
      maximum-pool-size: 64


server:
  port: ${FOOBAR_SERVICE_PORT_CUSTOMER:4040}
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}


foobar:
  rest:
    on-concurrency-error-retry-after: 1s

management:
  metrics:
    tags:
      foobar-service: foobar-customer
  endpoints:
    web:
      exposure:
        include:
          - '*'

