version: "3"

services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=.

volumes:
  postgres_data:
    driver: local

