spring:
  application:
    name: FoobarMarketplace
  main:
    banner-mode: off
  zipkin:
    enabled: false
  r2dbc:
    url: 'r2dbc:mariadb://${FOOBAR_MYSQL_HOST:localhost:3306}/foobar_marketplace'
    username: ${FOOBAR_MYSQL_USER:root}
    password: ${FOOBAR_MYSQL_PASS:.}
    pool:
      enabled: true
      initial-size: 1280
      max-size: 10240
  flyway:
    create-schemas: false
    fail-on-missing-locations: true
    baseline-on-migrate: true
    user: ${FOOBAR_MYSQL_USER:root}
    password: ${FOOBAR_MYSQL_PASS:.}
    url: 'jdbc:mariadb://${FOOBAR_MYSQL_HOST:localhost:3306}/foobar_marketplace'

server:
  port: ${FOOBAR_SERVICE_PORT_MARKETPLACE:4041}
  error:
    include-message: always
    include-binding-errors: always


feign:
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000


resilience4j:
  circuitbreaker:
    instances:
      seller-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 10
  retry:
    instances:
      seller-service:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException


logging:
  level:
    org.apache.kafka: error
    io.koosha.foobar: ${FOOBAR_LOG_LEVEL:info}
    org.mariadb.r2dbc.message.server: error


foobar:
  service:
    services:
      customer:
        url: ${FOOBAR_SERVICE_URL_CUSTOMER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_CUSTOMER:4040}
        retry: true
        limit: false
      seller:
        url: ${FOOBAR_SERVICE_URL_SELLER:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_SELLER:4043}
        retry: true
        limit: false
      warehouse:
        url: ${FOOBAR_SERVICE_URL_WAREHOUSE:http://localhost}
        port: ${FOOBAR_SERVICE_PORT_WAREHOUSE:4046}
        retry: true
        limit: false

  rest:
    on-concurrency-error-retry-after: 1s

management:
  metrics:
    tags:
      foobar-service: foobar-marketplace
  endpoints:
    web:
      exposure:
        include:
          - '*'
